### ISSUE TITLE
Support for 1.19.2

### ISSUE THREAD

**Issue by SpencerComputers** [Yochran/yoCore#24]
Will this ever be a thing? For now this is the error on join if anybody wants to contribute lol

```
14:31:53 WARN]: [yoCore] Task #10 for yoCore v1.0.1 generated an exception
java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "name" is null
        at me.yochran.yocore.ranks.Rank.getRank(Rank.java:49) ~[yoCore-1.0.3.jar:?]
        at me.yochran.yocore.player.yoPlayer.getRank(yoPlayer.java:30) ~[yoCore-1.0.3.jar:?]
        at me.yochran.yocore.scoreboard.ScoreboardSetter.scoreboard(ScoreboardSetter.java:103) ~[yoCore-1.0.3.jar:?]
        at me.yochran.yocore.runnables.ScoreboardUpdater.run(ScoreboardUpdater.java:22) ~[yoCore-1.0.3.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-211]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-211]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-211]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-211]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-211]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-211]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-211]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Yochran** [comment]
No— I've started school now and do not have time for development (look at my contribution activity). Unfortunately it will not be updated.
