### ISSUE TITLE
Report Error

### ISSUE THREAD

**Issue by Adriianh** [Yochran/yoCore#4]
Good morning. 

**Details:**

**Description:** The plugin starts correctly but always gives this error.
**Version:** 1.17.1 (Java 16, obviously)
**Software:** Purpur
**yoCore version:** latest

```
[13:26:03 WARN]: [yoCore] Task #20 for yoCore v1.0 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.command.PluginCommand.setExecutor(org.bukkit.command.CommandExecutor)" because the return value of "me.yochran.yocore.yoCore.getCommand(String)" is null
        at me.yochran.yocore.yoCore.registerCommands(yoCore.java:425) ~[yoCore-1.0.1.jar:?]
        at me.yochran.yocore.yoCore.access$100(yoCore.java:40) ~[yoCore-1.0.1.jar:?]
        at me.yochran.yocore.yoCore$1.run(yoCore.java:73) ~[yoCore-1.0.1.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1393]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1574) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1393]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Yochran** [comment]
Purpur has never been stated to be a supported .jar. Only Spigot & Paper will receive support.

**Comment by Adriianh** [comment]
> Purpur has never been stated to be a supported .jar. Only Spigot & Paper will receive support.

Purpur is a fork of paper, it only adds new patches for survival modes, there are no changes other than that.
