### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by Hugytor09YT** [Yochran/yoCore#7]
[14:24:59 WARN]: [yoCore] Task #401 for yoCore v1.0 generated an exception
java.lang.IllegalArgumentException: Name cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.16.5.jar:git-Paper-792]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.getWorld(CraftServer.java:1257) ~[patched_1.16.5.jar:git-Paper-792]
        at org.bukkit.Bukkit.getWorld(Bukkit.java:629) ~[patched_1.16.5.jar:git-Paper-792]
        at me.yochran.yocore.yoCore.registerServers(yoCore.java:266) ~[?:?]
        at me.yochran.yocore.yoCore.access$900(yoCore.java:40) ~[?:?]
        at me.yochran.yocore.yoCore$1.run(yoCore.java:88) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-792]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1432) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-792]
        at java.lang.Thread.run(Thread.java:831) [?:?

**Comment by Yochran** [comment]
Delete your servers.yml file, or check to make sure that you have the spawn and world name for every server set properly.
